# Generated by Django 4.2.10 on 2024-03-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-12-1'),
            preserve_default=False,
        ),
    ]
